[package]
name = "intern-arc"
description = "An interner that deallocates unused values"
homepage = "https://github.com/Actyx/intern-arc"
version = "0.1.0"
authors = ["Actyx AG <developer@actyx.io>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Actyx/intern-arc"
keywords = ["intern", "interner", "interning"]

[dependencies]
dashmap = "3.11"
once_cell = "1.3"
